heat_template_version: ocata 

description: >
    Simple ubuntu machine to test heat
    template guide

parameters:

    key_name:
        type: string
        description: Name of keypair to ssh to the instance
    instance_type:
        type: string
        description: flavor to be used for the instance
        default: m1.small
    image_id:
        type: string
        description: >
            Name or id of the image for the instance
            to be used

resources:

    ubuntu_server:
        type: OS::Nova::Server
        properties:
            image: { get_param: image_id }
            flavor: { get_param: instance_type }
            key_name: { get_param: key_name }

outputs:

    host_ip:
        description: IP of the machine
        value:
            str_replace:
                template: "IP:ip"
            params:
                ip: { get_attr: [ubuntu_server, first_address] }

