heat_template_version: ocata

description: >
  example ubuntu template with constraints
  for flavor values

parameters:

  key_name:
    type: string
    description: Name of keypair for ssh to instance

  image_id:
    type: string
    description: Name of image id of the image for booting instance

  instance_type:
    type: string
    label: Instance type
    description: Flavor to be used for launching the instance
    constraints:
      - allowed_values: [ m1.medium, m1.tiny ]
        description: values must be one of m1.medium or m1.tiny


resources:
 
  HeatUbuntu:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }

outputs:

  host_ip:
    description: IP of the instance
    value: { get_attr: [HeatUbuntu, first_address] }
 
      
